/// This file was autogenerated by running `Tools/generate-boilerplate`

extension Block {
  public init(
    operations: (inout OperationBuilder) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [])
    try OperationBuilder.build(operations).forEach(self.operations.append)
  }

  public init(
    _ t0: Type,
    operations: (inout OperationBuilder, MLIR.Value) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0])
    try OperationBuilder.build { builder in
      try operations(&builder, arguments[0])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type,
    operations: (inout OperationBuilder, MLIR.Value, MLIR.Value) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1])
    try OperationBuilder.build { builder in
      try operations(&builder, arguments[0], arguments[1])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type,
    operations: (inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2])
    try OperationBuilder.build { builder in
      try operations(&builder, arguments[0], arguments[1], arguments[2])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type,
    operations: (inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) throws ->
      Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3])
    try OperationBuilder.build { builder in
      try operations(&builder, arguments[0], arguments[1], arguments[2], arguments[3])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type,
    operations: (inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value)
      throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4])
    try OperationBuilder.build { builder in
      try operations(&builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type, _ t5: Type,
    operations: (
      inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value
    ) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4, t5])
    try OperationBuilder.build { builder in
      try operations(
        &builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4], arguments[5]
      )
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type, _ t5: Type, _ t6: Type,
    operations: (
      inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value,
      MLIR.Value, MLIR.Value
    ) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4, t5, t6])
    try OperationBuilder.build { builder in
      try operations(
        &builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4],
        arguments[5], arguments[6])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type, _ t5: Type, _ t6: Type, _ t7: Type,
    operations: (
      inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value,
      MLIR.Value, MLIR.Value, MLIR.Value
    ) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4, t5, t6, t7])
    try OperationBuilder.build { builder in
      try operations(
        &builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4],
        arguments[5], arguments[6], arguments[7])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type, _ t5: Type, _ t6: Type, _ t7: Type,
    _ t8: Type,
    operations: (
      inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value,
      MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value
    ) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4, t5, t6, t7, t8])
    try OperationBuilder.build { builder in
      try operations(
        &builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4],
        arguments[5], arguments[6], arguments[7], arguments[8])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type, _ t5: Type, _ t6: Type, _ t7: Type,
    _ t8: Type, _ t9: Type,
    operations: (
      inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value,
      MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value
    ) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4, t5, t6, t7, t8, t9])
    try OperationBuilder.build { builder in
      try operations(
        &builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4],
        arguments[5], arguments[6], arguments[7], arguments[8], arguments[9])
    }
    .forEach(self.operations.append)
  }

  public init(
    _ t0: Type, _ t1: Type, _ t2: Type, _ t3: Type, _ t4: Type, _ t5: Type, _ t6: Type, _ t7: Type,
    _ t8: Type, _ t9: Type, _ t10: Type,
    operations: (
      inout OperationBuilder, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value,
      MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value
    ) throws -> Void
  ) rethrows
  where
    Ownership == OwnedBySwift
  {
    self = Block(argumentTypes: [t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10])
    try OperationBuilder.build { builder in
      try operations(
        &builder, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4],
        arguments[5], arguments[6], arguments[7], arguments[8], arguments[9], arguments[10])
    }
    .forEach(self.operations.append)
  }

}
