
/**
 This file was autogenerated by
 ```
 $ pushd Utilities/BoilerplateGenerator
 $ swift run GenerateOperationProtocolExtensions
 $ popd
 ```
 */

extension OperationProtocol where Results == () {
  public static func results(from operation: Operation) -> Results {
    ()
  }
}

extension OperationProtocol where Results == (MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3], operation.results[4])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3], operation.results[4], operation.results[5])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3], operation.results[4], operation.results[5], operation.results[6])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3], operation.results[4], operation.results[5], operation.results[6], operation.results[7])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3], operation.results[4], operation.results[5], operation.results[6], operation.results[7], operation.results[8])
  }
}

extension OperationProtocol where Results == (MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value, MLIR.Value) {
  public static func results(from operation: Operation) -> Results {
    (operation.results[0], operation.results[1], operation.results[2], operation.results[3], operation.results[4], operation.results[5], operation.results[6], operation.results[7], operation.results[8], operation.results[9])
  }
}
