#!/bin/zsh

PROJECT_ROOT=$(dirname "$(dirname "${0:A}")")

function linked_libraries() {
  cat "$PROJECT_ROOT/Sources/$1/module.modulemap" |
    sed -n 's/[^"]*link "\([^"]*\)",*/install-\1/p'
}

INSTALL_TARGETS=install-mlir-headers

INSTALL_TARGETS+="\n$(linked_libraries CMLIR)"

case $1; in
"")
  ;;
"--include-standard-dialect")
  INSTALL_TARGETS+="\n$(linked_libraries CMLIRStandard)"
  ;;
*)
  echo "Unknown argument $1" >&2
  exit
  ;;
esac

echo $INSTALL_TARGETS | xargs
