#!/bin/zsh

PROJECT_ROOT=$(dirname "$(dirname "${0:A}")")

function linked_libraries() {
  cat "$1" | sed -n 's/[^"]*link "\([^"]*\)",*/install-\1/p'
}

INSTALL_TARGETS=install-mlir-headers

INSTALL_TARGETS+=""

while test ${#} -gt 0
do
  case $1; in
  "--include-mlir-core")
    INSTALL_TARGETS+="\n$(linked_libraries "$PROJECT_ROOT/Sources/CMLIR/module.modulemap")"
    ;;
  "--include-standard-dialect")
    INSTALL_TARGETS+="\n$(linked_libraries "$PROJECT_ROOT/Sources/CMLIRStandard/module.modulemap")"
    ;;
  "--include-modulemap")
    if test ${#} -eq 1; then
      echo "--include-modulemap requires a path"
      exit 1
    fi
    shift
    INSTALL_TARGETS+="\n$(linked_libraries "$1")"
    ;;
  *)
    echo "Unknown argument $1" >&2
    exit
    ;;
  esac
  shift
done

echo $INSTALL_TARGETS | sort | uniq | xargs
