#!/bin/bash

set -e

# Configuration
TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_ROOT=${PROJECT_ROOT:-$(cd "$TOOLS_ROOT" && cd $(git rev-parse --show-toplevel) && pwd)}
DEPENDENCIES_ROOT=${DEPENDENCIES_ROOT:-$PROJECT_ROOT/.dependencies}
PKG_CONFIG_ROOT=${PKG_CONFIG_ROOT:-/usr/local/lib/pkgconfig}
INSTALL_PATH=${INSTALL_PATH:-$DEPENDENCIES_ROOT/installed}
LLVM_COMMIT=${LLVM_COMMIT:-$(cat $TOOLS_ROOT/llvm-commit)}
LLVM_REPO=${LLVM_REPO:-https://github.com/llvm/llvm-project}
LLVM_REPO_PATH=${LLVM_REPO_PATH:-$DEPENDENCIES_ROOT/llvm-repo}
LLVM_PATH_IN_REPO=${LLVM_PATH_IN_REPO:-""}
LLVM_ADDITIONAL_CMAKE_ARGS=${LLVM_ADDITIONAL_CMAKE_ARGS:-""}
LLVM_ROOT="$LLVM_REPO_PATH/$LLVM_PATH_IN_REPO"
LLVM_BUILD_ROOT="$DEPENDENCIES_ROOT/llvm-build"
TOOLS_INSTALL_PATH="$DEPENDENCIES_ROOT/installed/tools"
PKG_CONFIG_PATH="$PKG_CONFIG_ROOT/LLVM-for-Swift.pc"
PKG_CONFIG=$(cat << EOF
prefix=$INSTALL_PATH

Name: LLVM for Swift
Description: LLVM, potentially with additional projects. Installed using Utilities/build-dependencies in MLIRSwift.
Version: local
Cflags: -I\${prefix}/include
Libs: -lc++ -lcurses $(
  # For some reason, linking the C++ standard libary explicitly is necessary on Linux but breaks the macOS build.
  [[ "$OSTYPE" == "darwin"* ]] || echo "-lstdc++"
) -L\${prefix}/lib
EOF
)

# If shell is interactive, prompt for comfirmation
echo "This script will perform the following tasks:"
if [[ -n "$LLVM_REPO" ]]; then
  # Invoke with LLVM_REPO="" to skip any repo-management logic
  echo " - Checkout commit ${LLVM_COMMIT} from ${LLVM_REPO} to ${LLVM_REPO_PATH}"
fi
echo " - Build LLVM from ${LLVM_ROOT}"
if [[ -n "$LLVM_ADDITIONAL_CMAKE_ARGS" ]]; then
  echo "   - Additional cmake arguments:"
  for ARG in $(echo $LLVM_ADDITIONAL_CMAKE_ARGS); do
    echo "       $ARG"
  done
fi
echo "   - Built products will be placed in ${LLVM_BUILD_ROOT}"
echo " - Install all available LLVM projects to ${INSTALL_PATH}"
echo " - Install necessary tools to ${TOOLS_INSTALL_PATH}"
echo " - Update ${PKG_CONFIG_PATH} to point to ${INSTALL_PATH}"
echo ""

if [[ "$NO_INTERACTION" != "true" ]]; then
  echo "Press enter to continue."
  read
fi

# Install swift-format'
if [[ -n "$TOOLS_INSTALL_PATH/swift-format" ]]; then
  echo "Installing swift-format"
  # `swift build` doesn't seem to actually build the swift-format executable (likely because it is a dependency), so we use `swift run`.
  swift run --package-path "$TOOLS_ROOT/SwiftFormat" -c release swift-format --version
  mkdir -p "$TOOLS_INSTALL_PATH"
  cp $(swift build --package-path "$TOOLS_ROOT/SwiftFormat" -c release --show-bin-path)/swift-format "$TOOLS_INSTALL_PATH"
fi

# Clone/checkout LLVM or other another project that includes LLVM
if [[ -n "$LLVM_REPO" ]]; then
  if [[ ! -d "$LLVM_REPO_PATH/.git" ]]; then
    echo "Setting up \"$LLVM_REPO\""
    # Set up repo without cloning
    mkdir -p "$LLVM_REPO_PATH"
    pushd "$LLVM_REPO_PATH" > /dev/null
      git init
      git remote add origin "$LLVM_REPO"
    popd > /dev/null
  fi
  # Checkout specified commit
  echo "Checking out \"$LLVM_COMMIT\""
  pushd "$LLVM_REPO_PATH" > /dev/null
    git fetch origin "$LLVM_COMMIT"
    git checkout -f "$LLVM_COMMIT"
    # This tool is meant to support repos which include LLVM as a submodule
    git submodule update --init
  popd > /dev/null
fi

# Build LLVM
cmake \
  -S "$LLVM_ROOT/llvm" \
  -B "$LLVM_BUILD_ROOT" \
  -G Ninja \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_PATH" \
  $([[ "$OSTYPE" == "darwin"* ]] && echo "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15") \
  -DLLVM_BUILD_EXAMPLES=OFF \
  -DLLVM_INSTALL_UTILS=OFF \
  -DLLVM_BUILD_TOOLS=OFF \
  -DLLVM_TARGETS_TO_BUILD=host \
  -DLLVM_ENABLE_PROJECTS=mlir \
  -DLLVM_ENABLE_OCAMLDOC=OFF \
  -DLLVM_ENABLE_BINDINGS=OFF \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Release} \
  $(echo $LLVM_ADDITIONAL_CMAKE_ARGS)
cmake \
  --build "$LLVM_BUILD_ROOT" \
  --target install

# Install the LLVM package config
if [[ -n "$PKG_CONFIG_ROOT" ]]; then
  echo "Writing pkg-config file to $PKG_CONFIG_PATH"
  if ! echo "$PKG_CONFIG" > "$PKG_CONFIG_PATH"; then
    echo "Could not create pkg-config file, please ensure $PKG_CONFIG_PATH is writable."
    exit 1
  fi
fi
