#!/bin/bash

# This script requires that `swift-format` is installed using `build-dependendencies`. It also standardizes which files are processed for formatting.

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd "$(git rev-parse --show-toplevel)" && pwd )"

function swift-format() {
  # TODO: Add --parallel once Swift 5.4 is released
  "$PROJECT_ROOT/.dependencies/installed/tools/swift-format" $@
}

if [[ "$1" == "--ci" ]]; then
  if [[ "$#" != "1" ]]; then
    echo "--ci cannot be used with any other arguments" 1>&2
    exit 1
  fi
  swift-format --mode format --in-place --recursive Sources
else
  swift-format $@
fi
